import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize,stats,segments,extractYears,matchesQuery,segmentKey,deduplicate,COLOR_RULES,attribute,eligible} from '../lib/market/model.ts';
const row=(seller:string,price:number,title='2005-2013 Chevy Corvette Driver Bottom Black Perforated Leather Seat Cover')=>normalize({seller,price,title,url:'https://example.com/product/'+seller+price,available:true});
test('own and reference sellers never affect primary benchmarks',()=>{
 const a=row('Texan Auto Seat Cover',200),b=row('AutoSeatReplacement',300),own=row('US Auto Nation',1),ref=row('RichmondAutoUpholstery',10000),unknown=row('Not registered',0.1);
 assert.deepEqual(stats([a,b,own,ref,unknown]),{count:2,sellers:2,min:200,max:300,mean:250,median:250});
});
test('references cannot create price recommendations',()=>{const s=segments([row('RichmondAutoUpholstery',10),row('AutoChampOfTexas',15)]);assert.equal(s[0].balanced,null);assert.equal(s[0].count,0);assert.equal(s[0].gap,true)});
test('recommendations need multiple primary sellers and three exact variants',()=>{assert.equal(segments([row('Texan Auto Seat Cover',200),row('Texan Auto Seat Cover',210),row('Texan Auto Seat Cover',220)])[0].balanced,null);const s=segments([row('Texan Auto Seat Cover',200),row('AutoSeatReplacement',210),row('AutoSeatReplacement',220)])[0];assert.equal(s.balanced,205.8)});
test('configuration, currency, finish and year differences do not share a segment',()=>{const a=row('Texan Auto Seat Cover',200),b=row('AutoSeatReplacement',300,'2005-2013 Chevy Corvette Driver Passenger Complete Black Leather Seat Covers');assert.notEqual(segmentKey(a),segmentKey(b));assert.notEqual(segmentKey(a),segmentKey({...a,currency:'CAD'}));assert.notEqual(segmentKey(a),segmentKey({...a,years:[2005]}))});
test('synthetic leather does not become leather',()=>{const r=row('AutoSeatReplacement',150,'2005-2013 Chevy Corvette Driver Bottom Black Synthetic Leather Seat Cover');assert.equal(r.material,'Synthetic Leather')});
test('structured fallback retains provenance and original aliases',()=>{const r=normalize({title:'2005-2013 Corvette Driver Bottom Seat Cover',seller:'Texan Auto Seat Cover',url:'https://example.com'},[{name:'Item specifics',text:'Color: Ebony; Material: Vinyl'}]);assert.equal(r.color,'Black');assert.equal(r.originalColor,'ebony');assert.equal(r.material,'Vinyl');assert.equal(r.colorEvidence,'Item specifics')});
test('variant material conflict is flagged and not priced',()=>{const r=normalize({title:'2005-2013 Corvette Driver Bottom Black Leather Seat Cover',seller:'Texan Auto Seat Cover',price:99,url:'https://example.com'},[{name:'Variation data',text:'Synthetic Leather'}]);assert.equal(r.material,'Unknown');assert.equal(eligible(r),false)});
test('fitment uses range overlap, rejecting unrelated generations',()=>{assert.equal(matchesQuery('1997-2003 Chevrolet Corvette','Chevy Corvette 2005–2013'),false);assert.equal(matchesQuery('2005-2013 Chevrolet Corvette','Chevy Corvette 2005–2013'),true);assert.equal(matchesQuery('2005-2013 Ford Mustang','Chevy Corvette 2005–2013'),false);assert.equal(extractYears('2005–2013').length,9)});
test('unknown data and out of stock items do not price',()=>{const r=row('Texan Auto Seat Cover',200);assert.equal(stats([{...r,available:false}]).count,0);assert.equal(stats([{...r,color:'Unknown'}]).count,0);assert.equal(stats([{...r,price:null}]).count,0)});
test('deduplication preserves distinct variants',()=>{const a=row('Texan Auto Seat Cover',200),b=row('Texan Auto Seat Cover',220);assert.equal(deduplicate([a,a,b]).length,2)});
test('color rules preserve configured OEM distinctions',()=>{assert.equal(attribute([{name:'title',text:'Ebony'}],{...COLOR_RULES,ebony:'Ebony'}).normalized,'Ebony')});
