import test from 'node:test';
import assert from 'node:assert/strict';
import {planSearch,matchesSearch,yearCoverage} from '../lib/market/search.ts';
import {normalize,type Research,type Listing} from '../lib/market/model.ts';
import {detectPriceEvents,mergeBaseline,makeTrack,applySnapshot,emptyIndex,isDue,DAY} from '../lib/market/tracking.ts';
import {saveResearch,acknowledge,claimTrack} from '../lib/market/service.ts';
import type {MarketStore} from '../lib/market/store.ts';
import type {MarketIndex,Snapshot} from '../lib/market/tracking.ts';
const now='2026-09-28T12:00:00.000Z';
const item=(seller='Texan Auto Seat Cover',price:number|null=200):Listing=>normalize({id:seller+'-variant',seller,title:'2005-2013 Chevy Corvette Driver Bottom Black Perforated Leather Seat Cover',price,url:'https://example.com/product',available:true,collectedAt:now});
const research=(id='scan-123456',rows=[item()]):Research=>({id,query:'Chevy Corvette 2005–2013',createdAt:now,listings:rows,sources:[{seller:'Texan Auto Seat Cover',count:rows.length,status:'success',message:'test',url:'https://example.com',collectedAt:now}]});
class MemoryStore implements MarketStore{
 kind='memory';index:MarketIndex=emptyIndex();revision='0';snapshots=new Map<string,Snapshot>();conflict=false;
 async read(){return{revision:this.revision,index:structuredClone(this.index)}}
 async snapshot(id:string){return this.snapshots.get(id)||null}
 async commit(revision:string|null,index:MarketIndex,snapshot?:Snapshot){if(this.conflict){this.conflict=false;this.revision=String(Number(this.revision)+1);return false}if(revision!==this.revision)return false;this.index=structuredClone(index);this.revision=String(Number(this.revision)+1);if(snapshot)this.snapshots.set(snapshot.id,structuredClone(snapshot));return true}
}
test('expands 2005–2013 to every year 2004–2014',()=>{const p=planSearch('Chevy Corvette 2005–2013');assert.deepEqual(p.years,[2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014]);assert.equal(p.searchTerms.length,12);assert.equal(p.product,'Chevy Corvette')});
test('single year includes both neighbors; shorthand and separated years work',()=>{assert.deepEqual(planSearch('Kia Stinger 2018').years,[2017,2018,2019]);assert.deepEqual(planSearch('Audi Q7 2010-12').years,[2009,2010,2011,2012,2013]);assert.deepEqual(planSearch('Honda Fit 2008 2010').years,[2007,2008,2009,2010,2011])});
test('generic vehicle terms work without a hardcoded vehicle list',()=>{assert.equal(matchesSearch('2017 Kia Stinger Driver Seat Cover','Kia Stinger 2018'),true);assert.equal(matchesSearch('2019 Kia Stinger Driver Seat Cover','Kia Stinger 2018'),true);assert.equal(matchesSearch('2020 Kia Stinger Driver Seat Cover','Kia Stinger 2018'),false);assert.equal(matchesSearch('2018 Kia Sportage','Kia Stinger 2018'),false)});
test('brand alias, token boundaries and invalid ranges are handled',()=>{assert.equal(planSearch('Chevy Corvette 2005-2013').key,planSearch('Chevrolet Corvette 2005–2013').key);assert.equal(matchesSearch('2010 Dodge Program cover','Dodge Ram 2010'),false);assert.throws(()=>planSearch('Corvette 2013-2005'));assert.throws(()=>planSearch('2005–2013'));assert.deepEqual(planSearch('Honda Fit').years,[])});
test('coverage includes intervening observed years but invents none',()=>{const p=planSearch('Corvette 2005-2007');const c=yearCoverage(['2005-2006 Corvette'],p);assert.equal(c.find(y=>y.year===2006)?.found,true);assert.equal(c.find(y=>y.year===2004)?.found,false);assert.equal(c.find(y=>y.year===2008)?.adjacent,true)});
test('same variant price reduction below a fresh own offer generates alert',()=>{const events=detectPriceEvents([item(undefined,200)],[item(undefined,150),item('US Auto Nation',180)],'track','run',now);assert.equal(events.length,1);assert.equal(events[0].kind,'undercut');assert.equal(events[0].ownPrice,180)});
test('own and reference price changes cannot generate competitor alerts',()=>{for(const seller of ['US Auto Nation','RichmondAutoUpholstery','AutoChampOfTexas'])assert.equal(detectPriceEvents([item(seller,200)],[item(seller,150)],'t','r',now).length,0)});
test('no undercut against stale, unavailable, other currency or other configuration own data',()=>{const own=item('US Auto Nation',180);for(const altered of [{...own,collectedAt:'2026-09-20T00:00:00Z'},{...own,available:false},{...own,currency:'CAD'},{...own,configuration:'Front pair · complete'}])assert.equal(detectPriceEvents([item()],[item(undefined,150),altered],'t','r',now)[0].kind,'price_down')});
test('missing, unknown and unchanged prices produce no fake changes',()=>{assert.equal(detectPriceEvents([item()],[],'t','r',now).length,0);assert.equal(detectPriceEvents([item()],[item(undefined,null)],'t','r',now).length,0);assert.equal(detectPriceEvents([item()],[item()],'t','r',now).length,0);assert.equal(detectPriceEvents([item()],[{...item(undefined,150),currency:'EUR'}],'t','r',now).length,0)});
test('failed and partial scans preserve last known comparison baseline',()=>{assert.equal(mergeBaseline([item()],[])[0].price,200);assert.equal(mergeBaseline([item()],[item(undefined,null)])[0].price,200);assert.equal(mergeBaseline([item()],[item(undefined,190)])[0].price,190)});
test('24-hour due state respects pause and active lease',()=>{const t=makeTrack('Corvette 2005-2013',now);t.nextRefreshAt=new Date(Date.parse(now)+DAY).toISOString();assert.equal(isDue(t,Date.parse(now)+DAY-1),false);assert.equal(isDue(t,Date.parse(now)+DAY),true);assert.equal(isDue({...t,enabled:false},Date.parse(now)+2*DAY),false);assert.equal(isDue({...t,leaseUntil:new Date(Date.parse(now)+3*DAY).toISOString()},Date.parse(now)+2*DAY),false)});
test('snapshot keeps observations separate from retained baseline and schedules next refresh',()=>{const track=makeTrack('Chevy Corvette 2005–2013',now);const first=applySnapshot(emptyIndex(),track,research(),null);const second=applySnapshot(first.index,first.index.tracks[0],{...research('scan-second',[]),createdAt:'2026-09-29T12:00:00Z'},first.snapshot);assert.equal(second.snapshot.listings.length,0);assert.equal(second.snapshot.baseline.length,1);assert.equal(second.index.tracks[0].nextRefreshAt,'2026-09-30T12:00:00.000Z')});
test('repository transactions retry conflicts and saving same run is idempotent',async()=>{const store=new MemoryStore();store.conflict=true;const saved=await saveResearch(store,research());assert.equal(store.index.runs.length,1);await saveResearch(store,research());assert.equal(store.index.runs.length,1);assert.equal(store.index.tracks.length,1);assert.equal(saved.trackId,store.index.tracks[0].id)});
test('price events persist and acknowledgement updates team unread counters',async()=>{const store=new MemoryStore();await saveResearch(store,research());await saveResearch(store,{...research('scan-next',[item(undefined,150)]),createdAt:'2026-09-29T12:00:00Z'});assert.equal(store.index.tracks[0].unread,1);await acknowledge(store,[store.index.notifications[0].id]);assert.equal(store.index.tracks[0].unread,0);assert.ok(store.index.notifications[0].readAt)});
test('normalization edits do not defer the daily scan or generate price events',()=>{const track=makeTrack('Chevy Corvette 2005–2013',now);const first=applySnapshot(emptyIndex(),track,research(),null);const second=applySnapshot(first.index,first.index.tracks[0],{...research('scan-edited'),createdAt:'2026-09-28T15:00:00Z',kind:'normalization'},first.snapshot);assert.equal(second.index.tracks[0].nextRefreshAt,first.index.tracks[0].nextRefreshAt);assert.equal(second.snapshot.events.length,0)});
test('leases prevent overlapping scheduled and manual collectors',async()=>{const store=new MemoryStore();await saveResearch(store,research());const t=store.index.tracks[0];assert.ok(await claimTrack(store,t.id,true));assert.equal(await claimTrack(store,t.id,true),null)});
