'use client';
import {useEffect,useState} from 'react';
import {Bell,ArrowDownRight,ArrowUpRight,Clock3,Database,CheckCheck,RefreshCw,Pause,Play,ExternalLink,TriangleAlert} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Empty,date} from './market-ui';
import {money,type Research} from '@/lib/market/model';
import type {MarketIndex,TrackedProduct,PriceEvent} from '@/lib/market/tracking';
type SeriesPoint={runId:string;at:string;price:number|null;currency:string|null;observed:boolean;available:boolean|null};
export function DataHistory({index,activeTrack,research,onTrack,onRun,onAcknowledge,onToggle,onRefresh}:{index:MarketIndex;activeTrack:string;research:Research;onTrack:(id:string)=>void;onRun:(id:string)=>void;onAcknowledge:(ids:string[])=>void;onToggle:(id:string,enabled:boolean)=>void;onRefresh:(query:string)=>void}){
 const track=index.tracks.find(t=>t.id===activeTrack)||index.tracks[0];
 const runs=index.runs.filter(r=>r.trackId===track?.id);const alerts=index.notifications.filter(n=>n.trackId===track?.id);
 const [listingId,setListingId]=useState(''),[series,setSeries]=useState<SeriesPoint[]>([]),[seriesError,setSeriesError]=useState(''),[loading,setLoading]=useState(false),[historyPage,setHistoryPage]=useState(1),[alertPage,setAlertPage]=useState(1),[latest,setLatest]=useState<Research|null>(null);
 useEffect(()=>{setListingId('');setSeries([]);setHistoryPage(1);setAlertPage(1);setLatest(null);setSeriesError('');if(!track?.latestRunId)return;let live=true;fetch('/api/research?id='+encodeURIComponent(track.latestRunId)).then(r=>{if(!r.ok)throw new Error();return r.json()}).then((d:any)=>{if(live){setLatest(d);setListingId(d.listings.find((r:any)=>r.price!==null)?.id||'')}}).catch(()=>{if(live)setSeriesError('Latest listing data could not be loaded.')});return()=>{live=false}},[track?.id,track?.latestRunId]);
 useEffect(()=>{if(!track||!listingId)return;const controller=new AbortController();setLoading(true);setSeriesError('');fetch('/api/tracking?trackId='+encodeURIComponent(track.id)+'&listingId='+encodeURIComponent(listingId),{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then((d:any)=>setSeries(d.series)).catch(e=>{if(e.name!=='AbortError')setSeriesError('Price history could not be loaded. Try selecting the variant again.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[track?.id,listingId,track?.latestRunId]);
 if(!track)return <section className="panel"><Empty title="Start tracking your first vehicle">Run Analyze Market. The search, observed variants, future refreshes, and price history will be saved in the shared repository.</Empty></section>;
 const unread=alerts.filter(n=>!n.readAt);const priced=series.filter(p=>p.price!==null);const priceCurrency=priced[0]?.currency||'USD';
 return <div className="history-workspace"><section className="panel tracked-heading"><div><span className="eyebrow">CENTRAL DATA HISTORY</span><h2>{track.name}</h2><p>Requested {track.plan.requestedMin??'all'}–{track.plan.requestedMax??'years'} · Search window {track.plan.minYear??'all'}–{track.plan.maxYear??'years'}</p></div><div className="history-actions"><Select value={track.id} onValueChange={onTrack}><SelectTrigger aria-label="Tracked vehicle"><SelectValue/></SelectTrigger><SelectContent>{index.tracks.map(t=><SelectItem key={t.id} value={t.id}>{t.name} · {t.plan.requestedMin??'All'}–{t.plan.requestedMax??'years'}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>onToggle(track.id,!track.enabled)}>{track.enabled?<Pause size={15}/>:<Play size={15}/>} {track.enabled?'Pause tracking':'Resume tracking'}</Button><Button onClick={()=>onRefresh(track.query)}><RefreshCw size={15}/> Refresh now</Button></div></section>
 <div className="tracking-summary"><div><Clock3 size={18}/><span>Last attempt<strong>{track.lastAttemptAt?date(track.lastAttemptAt):'Waiting for first scan'}</strong></span></div><div><RefreshCw size={18}/><span>Next refresh due<strong>{track.enabled?date(track.nextRefreshAt):'Paused'}</strong></span></div><div><Database size={18}/><span>Saved snapshots<strong>{runs.length}</strong></span></div><div><Bell size={18}/><span>Unread notifications<strong>{unread.length}</strong></span></div></div>
 <div className="info-note"><Clock3 size={18}/><p>GitHub checks for due models hourly and refreshes each one after 24 hours. Price changes appear after a scan; this is not real-time monitoring. Scheduler delays are possible. Failed sources retain their last observed baseline without replacing current results with stale prices.</p></div>
 <section className="panel"><div className="panel-heading"><div><h2>Competitor updates <span className="count-pill">{alerts.length}</span></h2><p>Price changes for primary competitors. Reference and owned accounts cannot trigger competitor price alerts.</p></div><Button variant="outline" size="sm" disabled={!unread.length} onClick={()=>onAcknowledge(unread.map(n=>n.id))}><CheckCheck size={16}/> Mark read for team</Button></div>{alerts.length?<><div className="notification-list">{alerts.slice((alertPage-1)*20,alertPage*20).map(n=><Notification key={n.id} event={n} onRun={onRun}/>)}</div><div className="table-footer"><span>{alerts.length} recorded changes</span><div><Button variant="outline" size="sm" disabled={alertPage===1} onClick={()=>setAlertPage(p=>p-1)}>Previous</Button><span>{alertPage}</span><Button variant="outline" size="sm" disabled={alertPage*20>=alerts.length} onClick={()=>setAlertPage(p=>p+1)}>Next</Button></div></div></>:<Empty title="No price changes detected yet">The first scan establishes a baseline. Future scans compare the same listing variants and currencies.</Empty>}</section>
 <section className="panel price-history-panel"><div className="panel-heading"><div><h2>Variant price history</h2><p>Actual observations from the latest 60 snapshots. Missing observations remain gaps.</p></div></div><div className="history-picker"><Select value={listingId} onValueChange={setListingId}><SelectTrigger aria-label="Variant price history"><SelectValue placeholder="Choose a listing variant"/></SelectTrigger><SelectContent>{(latest?.listings||[]).map(r=><SelectItem key={r.id} value={r.id}>{r.seller} · {r.title} · {r.variant}</SelectItem>)}</SelectContent></Select></div>{loading?<p className="history-loading">Loading observations…</p>:seriesError?<p role="alert" className="history-loading red-text">{seriesError}</p>:series.length?<><PriceChart series={series}/><Table><TableHeader><TableRow><TableHead>OBSERVED AT</TableHead><TableHead>ITEM PRICE</TableHead><TableHead>OBSERVATION</TableHead><TableHead>SNAPSHOT</TableHead></TableRow></TableHeader><TableBody>{series.slice().reverse().map(p=><TableRow key={p.runId}><TableCell>{date(p.at)}</TableCell><TableCell>{money(p.price,p.currency||priceCurrency)}</TableCell><TableCell>{!p.observed?'Not observed':p.available===false?'Out of stock':p.price===null?'Exact price unavailable':'Price published'}</TableCell><TableCell><Button variant="ghost" size="sm" onClick={()=>onRun(p.runId)}>Open snapshot <ArrowUpRight size={14}/></Button></TableCell></TableRow>)}</TableBody></Table></>:<Empty title="No price observations for this variant"/>}</section>
 <section className="panel"><div className="panel-heading"><div><h2>All saved research</h2><p>Each scan is an immutable historical snapshot. Select one to reopen its complete analysis.</p></div><a href="https://github.com/aliahmadi1382/Market_Lens/tree/market-data/market" target="_blank" rel="noreferrer" className="text-button">Shared archive <ExternalLink size={14}/></a></div><Table><TableHeader><TableRow><TableHead>COLLECTED</TableHead><TableHead>VARIANTS</TableHead><TableHead>SOURCE COVERAGE</TableHead><TableHead>PRICE CHANGES</TableHead><TableHead>TYPE</TableHead><TableHead/></TableRow></TableHeader><TableBody>{runs.slice((historyPage-1)*20,historyPage*20).map(r=><TableRow key={r.id}><TableCell>{date(r.createdAt)}</TableCell><TableCell>{r.listingCount}</TableCell><TableCell>{r.sourceErrors} errors · {r.sourcePartial} partial</TableCell><TableCell>{r.eventCount}</TableCell><TableCell>{r.kind}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>onRun(r.id)}>Open analysis</Button></TableCell></TableRow>)}</TableBody></Table><div className="table-footer"><span>{runs.length} snapshots · original source timestamps retained</span><div><Button variant="outline" size="sm" disabled={historyPage===1} onClick={()=>setHistoryPage(p=>p-1)}>Previous</Button><span>{historyPage}</span><Button variant="outline" size="sm" disabled={historyPage*20>=runs.length} onClick={()=>setHistoryPage(p=>p+1)}>Next</Button></div></div></section>
 </div>
}
function Notification({event:n,onRun}:{event:PriceEvent;onRun:(id:string)=>void}){return <article className={'notification '+(n.readAt?'':'unread')}><span className={'notification-icon '+n.kind}>{n.kind==='undercut'?<TriangleAlert size={19}/>:n.kind==='price_down'?<ArrowDownRight size={19}/>:<ArrowUpRight size={19}/>}</span><div><div className="notification-title"><strong>{n.seller} changed its price</strong><time>{date(n.observedAt)}</time></div><p>{n.title}</p><div className="notification-prices"><span>{money(n.oldPrice,n.currency)}</span> → <strong>{money(n.newPrice,n.currency)}</strong>{n.kind==='undercut'&&<b>Lower than our {money(n.ownPrice,n.currency)}</b>}</div><small>Item prices only · same configuration, fitment, and currency</small></div><Button variant="ghost" size="sm" onClick={()=>onRun(n.runId)} aria-label="Open notification snapshot"><ArrowUpRight size={16}/></Button></article>}
function PriceChart({series}:{series:SeriesPoint[]}){
 const currencies=[...new Set(series.filter(p=>p.price!==null&&p.currency).map(p=>p.currency!))];
 return <>{currencies.map(currency=><div key={currency}><p className="history-loading">{currency} · published item price</p><CurrencyChart series={series.map(p=>p.currency===currency?p:{...p,price:null})} currency={currency}/></div>)}</>;
}
function CurrencyChart({series,currency}:{series:SeriesPoint[];currency:string}){
 const values=series.filter(p=>p.price!==null);if(!values.length)return null;const min=Math.min(...values.map(p=>p.price!)),max=Math.max(...values.map(p=>p.price!));const span=max-min||Math.max(max*.05,1);const width=800,height=170;
 const first=Date.parse(series[0].at),duration=Date.parse(series.at(-1)!.at)-first||1;
 const x=(p:SeriesPoint)=>45+(Date.parse(p.at)-first)/duration*(width-80);const y=(p:SeriesPoint)=>height-25-(p.price!-min)/span*(height-60);
 return <div className="price-chart"><div><span>{money(max,values[0].currency||'USD')}</span><span>{money(min,values[0].currency||'USD')}</span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Observed price history: ${values.length} prices, ${money(min,currency)} to ${money(max,currency)}. Missing observations are not connected.`}><line x1="35" x2="780" y1="145" y2="145" stroke="#e4eaf3"/>{series.map((p,i)=>p.price===null?null:<g key={p.runId}>{i>0&&series[i-1].price!==null&&series[i-1].currency===p.currency&&<line x1={x(series[i-1])} y1={y(series[i-1])} x2={x(p)} y2={y(p)} stroke="#2867df" strokeWidth="2.5"/>}<circle cx={x(p)} cy={y(p)} r="4" fill="#2867df"><title>{date(p.at)}: {money(p.price,p.currency||'USD')}</title></circle></g>)}</svg><footer><span>{date(series[0].at)}</span><span>{date(series.at(-1)!.at)}</span></footer></div>
}
