'use client';
import {FileSearch,Search,Package,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {money,type Listing} from '@/lib/market/model';
export const SWATCH:Record<string,string>={Black:'#25272b',Tan:'#c6a580',Gray:'#9fa4af',Shale:'#c8c3b2',Neutral:'#d0c3b3',Red:'#be4748',Blue:'#466aa7',Brown:'#775445',White:'#f7f7f7',Unknown:'#d2d7e0'};
export const date=(d:string)=>d?new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not collected';
export function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="filter-pick"><SelectValue placeholder={label}/></SelectTrigger><SelectContent><SelectItem value="all">All {label.toLowerCase()}</SelectItem>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export function Empty({title,children}:{title:string;children?:React.ReactNode}){return <div className="empty-state"><FileSearch size={30}/><h3>{title}</h3><p>{children||'Try a different search or clear a filter.'}</p></div>}
export function Stat({label,value,sub,icon:Icon,tone}:{label:string;value:string|number;sub:string;icon:typeof Search;tone?:string}){return <div className="stat"><div className="stat-top"><span>{label}</span><Icon size={17}/></div><div className={'stat-value '+(tone||'')}>{value}</div><div className="stat-sub">{sub}</div></div>}
export function ListingTable({rows,all,ownView,group,setGroup,listingSearch,setListingSearch,sort,setSort,page,setPage,inspect}:{rows:Listing[];all:Listing[];ownView:boolean;group:string;setGroup:(v:string)=>void;listingSearch:string;setListingSearch:(v:string)=>void;sort:string;setSort:(v:string)=>void;page:number;setPage:(v:number)=>void;inspect:(r:Listing)=>void}){return <section className="panel listings-panel"><div className="panel-heading"><div><h2>{ownView?'Your collected listings':'Market listings'} <span className="count-pill">{rows.length}</span></h2><p>Open a listing to inspect its variant, source, and extracted attributes.</p></div><div className="list-tools"><div className="small-search"><Search size={15}/><Input aria-label="Filter listings" placeholder="Find in results…" value={listingSearch} onChange={e=>setListingSearch(e.target.value)}/></div><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort listings"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="default">Source order</SelectItem><SelectItem value="low">Price: low to high</SelectItem><SelectItem value="high">Price: high to low</SelectItem><SelectItem value="seller">Seller name</SelectItem></SelectContent></Select></div></div>
 {!ownView&&<Tabs value={group} onValueChange={setGroup} className="listing-tabs"><TabsList variant="line">{[['all','All listings'],['primary','Primary competitors'],['own','Our listings'],['reference','Color & material references']].map(([g,label])=><TabsTrigger key={g} value={g}>{label}<span>{all.filter(r=>g==='all'||r.group===g).length}</span></TabsTrigger>)}</TabsList></Tabs>}
 {rows.length?<><Table><TableHeader><TableRow><TableHead>PRODUCT / VARIANT</TableHead><TableHead>SELLER</TableHead><TableHead>COLOR & MATERIAL</TableHead><TableHead>CONFIGURATION</TableHead><TableHead className="right">ITEM PRICE</TableHead><TableHead className="right">DETAILS</TableHead></TableRow></TableHeader><TableBody>{rows.slice((page-1)*10,page*10).map(r=><TableRow key={r.id}><TableCell><button className="product-cell" onClick={()=>inspect(r)}><span className="product-icon"><Package size={20}/></span><span><strong>{r.title}</strong><small>{r.variant&&r.variant!=='Default Title'?r.variant:r.years.length?`${Math.min(...r.years)}–${Math.max(...r.years)}`:'Review fitment'}{r.available===false?' · Out of stock':''}</small></span></button></TableCell><TableCell><span className="seller-name">{r.seller}</span><span className={'group-label '+r.group}>{r.group==='primary'?'Price competitor':r.group==='own'?'Your account':r.group==='reference'?'Reference only':'Unclassified'}</span></TableCell><TableCell><span className="color-label"><i style={{background:SWATCH[r.color]||'#c6cbd4'}}/>{r.color}</span><small className="block muted">{r.material}</small></TableCell><TableCell><span>{r.configuration}</span><small className="block muted">{r.finish}</small></TableCell><TableCell className="right"><strong className="price-number">{money(r.price,r.currency)}</strong><small className="block muted">{r.price===null?'Exact price unavailable':r.shipping===null?'Shipping unknown':'+'+money(r.shipping)+' shipping'}</small></TableCell><TableCell className="right"><Button variant="ghost" size="icon" aria-label={'Inspect '+r.title} onClick={()=>inspect(r)}><ArrowUpRight size={17}/></Button></TableCell></TableRow>)}</TableBody></Table><div className="table-footer"><span>{(page-1)*10+1}–{Math.min(page*10,rows.length)} of {rows.length} variants</span><div><Button variant="outline" size="sm" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>{page} / {Math.ceil(rows.length/10)}</span><Button variant="outline" size="sm" disabled={page*10>=rows.length} onClick={()=>setPage(page+1)}>Next</Button></div></div></>:<Empty title="No listings in this view">Clear filters or research another product. A missing result does not prove that a seller has no matching products.</Empty>}
 </section>}
