'use client';
import {useEffect,useMemo,useState} from 'react';
import {Bell,Activity,ArrowDownToLine,ArrowRight,ArrowUpRight,BarChart3,Check,ChevronRight,Clock3,ExternalLink,Globe2,Layers3,LayoutDashboard,LoaderCircle,Package,Palette,Search,ShieldCheck,SlidersHorizontal,Sparkles,Target,Users,Info,TriangleAlert,RefreshCw,ScanLine} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarTrigger} from '@/components/ui/sidebar';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {COLLECTION_SOURCES,SELLERS,GROUP_NAMES,COLOR_RULES,attribute,stats,segments,segmentKey,eligible,money,deduplicate,type Listing,type Research,type SourceStatus,type Group} from '@/lib/market/model';
import {Pick,Empty,Stat,ListingTable,SWATCH,date} from './market-ui';
import {KnownItems} from './known-items';
import {DataHistory} from './history-view';
import {CoverageSummary,SourceReports,AccountLinks} from './source-coverage';
import {planSearch,yearCoverage} from '@/lib/market/search';
import {emptyIndex,type MarketIndex} from '@/lib/market/tracking';
import initialData from '@/data/initial.json';
type View='history'|'overview'|'pricing'|'coverage'|'own'|'directory';
const NAV=[{key:'history',label:'Data History',icon:Clock3},{key:'overview',label:'Market overview',icon:LayoutDashboard},{key:'pricing',label:'Price intelligence',icon:BarChart3},{key:'coverage',label:'Catalog coverage',icon:Layers3},{key:'own',label:'Our listings',icon:Package},{key:'directory',label:'Competitor directory',icon:Users}] as const;
export default function Home(){
 const [research,setResearch]=useState<Research>(initialData as Research),[query,setQuery]=useState(initialData.query),[view,setView]=useState<View>('overview'),[group,setGroup]=useState('all'),[color,setColor]=useState('all'),[material,setMaterial]=useState('all'),[config,setConfig]=useState('all'),[year,setYear]=useState('all'),[seller,setSeller]=useState('all'),[currency,setCurrency]=useState('all'),[listingSearch,setListingSearch]=useState(''),[sort,setSort]=useState('default'),[page,setPage]=useState(1),[selected,setSelected]=useState<Listing|null>(null),[sourceOpen,setSourceOpen]=useState(false),[rulesOpen,setRulesOpen]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[activeSources,setActiveSources]=useState<SourceStatus[]>([]),[error,setError]=useState(''),[unsaved,setUnsaved]=useState(false),[history,setHistory]=useState<{id:string;query:string;createdAt:string;listingCount:number}[]>([]),[exporting,setExporting]=useState(false),[rulesText,setRulesText]=useState(JSON.stringify(COLOR_RULES,null,2)),[ruleError,setRuleError]=useState('');
 const [tracking,setTracking]=useState<MarketIndex>(emptyIndex),[activeTrack,setActiveTrack]=useState('');
 const unreadTotal=tracking.notifications.filter(n=>!n.readAt).length;
 let pendingPlan:ReturnType<typeof planSearch>|null=null,queryError='';try{pendingPlan=planSearch(query)}catch(e){queryError=e instanceof Error?e.message:'Invalid query'}
 const currentPlan=research.searchPlan||planSearch(research.query);
 const coverage=yearCoverage(research.listings.map(r=>r.title),currentPlan);
 async function refreshTracking(){try{const r=await fetch('/api/tracking');const data:any=await r.json();if(!r.ok)throw new Error(data.error);setTracking(data);setActiveTrack(id=>id||data.tracks[0]?.id||'')}catch(e){setError(e instanceof Error?e.message:'Shared tracking could not be loaded.')}}
 async function trackingAction(action:Record<string,unknown>){try{const r=await fetch('/api/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);await refreshTracking()}catch(e){toast.error(e instanceof Error?e.message:'Tracking update failed')}}
 useEffect(()=>{refreshTracking();const timer=setInterval(refreshTracking,60000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{fetch('/api/research').then(r=>r.json()).then((d:any)=>{if(d.research){setResearch(d.research);setQuery(d.research.query)}setHistory(d.history||[]);if(d.warning)setError(d.warning)}).catch(()=>setError('Saved research could not be loaded. Showing the bundled public snapshot.'));},[]);
 const all=research.listings;
 const currencies=[...new Set(all.map(r=>r.currency))];
 const filtered=useMemo(()=>all.filter(r=>(color==='all'||r.color===color)&&(material==='all'||r.material===material)&&(config==='all'||r.configuration===config)&&(year==='all'||r.years.includes(Number(year)))&&(seller==='all'||r.seller===seller)&&(currency==='all'||r.currency===currency)),[all,color,material,config,year,seller,currency]);
 const comparable=filtered.filter(eligible),metrics=stats(filtered),seg=segments(filtered),gaps=seg.filter(s=>s.gap),knownSegments=new Set(filtered.filter(r=>r.color!=='Unknown'&&r.material!=='Unknown').map(r=>r.color+'|'+r.material));
 const primary=filtered.filter(r=>r.group==='primary');
 const rows=useMemo(()=>{const g=view==='own'?'own':group;const r=filtered.filter(r=>(g==='all'||r.group===g)&&(!listingSearch||[r.title,r.seller,r.variant].join(' ').toLowerCase().includes(listingSearch.toLowerCase())));if(sort==='low')r.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));if(sort==='high')r.sort((a,b)=>(b.price??-Infinity)-(a.price??-Infinity));if(sort==='seller')r.sort((a,b)=>a.seller.localeCompare(b.seller));return r;},[filtered,view,group,listingSearch,sort]);
 useEffect(()=>{setPage(1)},[view,group,color,material,config,year,seller,listingSearch,sort,currency]);
 const sourceList=busy?activeSources:research.sources;
 const observedSellerCount=new Set(all.map(r=>r.seller)).size;
 function reset(){setColor('all');setMaterial('all');setConfig('all');setYear('all');setSeller('all');setCurrency('all');setListingSearch('');setGroup('all')}
 async function save(r:Research){try{const response=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});const d:any=await response.json();if(!response.ok)throw new Error(d.error);setResearch(d);setUnsaved(false);setHistory(h=>[{id:d.id,query:d.query,createdAt:d.createdAt,listingCount:d.listings.length},...h].slice(0,30));setError('');setActiveTrack(d.trackId||'');await refreshTracking();if(d.events?.length)toast.info(`${d.events.length} competitor price changes recorded.`);return true}catch(e){setUnsaved(true);setError(e instanceof Error?e.message:'Could not save research');return false}}
 async function analyze(e?:React.FormEvent,overrideQuery?:string){
  e?.preventDefault();if(busy)return;const searchQuery=(overrideQuery||query).trim();let searchPlan;try{searchPlan=planSearch(searchQuery)}catch(e){toast.error(e instanceof Error?e.message:'Invalid search');return}
  setQuery(searchQuery);setBusy(true);setError('');setProgress(0);setActiveSources([]);reset();
  try{const reserve=await fetch('/api/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'track',query:searchQuery})});const data:any=await reserve.json();if(!reserve.ok)throw new Error(data.error);setActiveTrack(data.id);await refreshTracking()}catch(e){setError(e instanceof Error?e.message:'Shared tracking could not be registered.');setBusy(false);return}
  const sources=COLLECTION_SOURCES,collected:Listing[]=[],reports:SourceStatus[]=[];
  for(let offset=0;offset<sources.length;offset+=3)await Promise.all(sources.slice(offset,offset+3).map(async source=>{try{const response=await fetch('/api/collect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:searchQuery,sourceId:source.id})});const data:any=await response.json();if(!response.ok)throw new Error(data.error);collected.push(...data.listings);reports.push(data.source);setActiveSources(p=>[...p,data.source])}catch(e){const failed:SourceStatus={sourceId:source.id,channel:source.channel,seller:source.seller,outcome:'failed',status:'error',count:0,message:e instanceof Error?e.message:'Source unavailable',url:source.url,collectedAt:new Date().toISOString()};reports.push(failed);setActiveSources(p=>[...p,failed])}finally{setProgress(p=>p+1)}}));
  const result:Research={id:crypto.randomUUID(),query:searchQuery,createdAt:new Date().toISOString(),listings:deduplicate(collected),sources:reports,searchPlan,kind:'analysis'};setResearch(result);setView('overview');const saved=await save(result);setBusy(false);
  if(saved){const failed=reports.filter(s=>s.status==='error').length;if(reports.every(s=>s.status==='error')){toast.error('All sources failed or were blocked. The failure report was saved.');setSourceOpen(true);}else if(!result.listings.length){toast.warning('No matching listings were collected. Review source coverage before treating this as an empty market.');setSourceOpen(true);}else toast.success(`${result.listings.length} observations saved. ${failed} sources unavailable; see source results.`);}
 }
 async function exportData(){setExporting(true);try{const response=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...research,listings:filtered})});if(!response.ok)throw new Error();const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='marketlens-research.xlsx';a.click();URL.revokeObjectURL(url);toast.success('Research exported with sources and comparison rules.')}catch{toast.error('Export could not be completed. Please retry.')}finally{setExporting(false)}}
 async function loadHistory(id:string){try{const response=await fetch('/api/research?id='+encodeURIComponent(id));const r:any=await response.json();if(!response.ok)throw new Error();setResearch(r);setQuery(r.query);reset();setUnsaved(false);setError('');setView('overview')}catch{toast.error('This saved research could not be loaded.')}}
 async function applyRules(){try{const rules=JSON.parse(rulesText);if(!rules||Array.isArray(rules)||typeof rules!=='object'||Object.entries(rules).some(([k,v])=>!k||typeof v!=='string'||!v||k.length>60||v.length>60)||Object.keys(rules).length>100)throw new Error('Use a JSON object with up to 100 text aliases.');const r={...research,id:crypto.randomUUID(),kind:'normalization' as const,listings:all.map(row=>{const c=attribute([{name:'Custom color rule',text:row.originalColor}],rules);return {...row,color:c.normalized,colorEvidence:c.evidence==='Custom color rule'?c.evidence:row.colorEvidence}})};setResearch(r);await save(r);setRulesOpen(false);setRuleError('');toast.success('Color rules applied to this research snapshot.')}catch(e){setRuleError(e instanceof Error?e.message:'Invalid rules')}}
 const filtersActive=[color,material,config,year,seller].some(v=>v!=='all');
 const title={history:'Data History',overview:'Market overview',pricing:'Price intelligence',coverage:'Catalog coverage',own:'Our listings',directory:'Competitor directory'}[view];
 const listingTable=<ListingTable rows={rows} all={filtered} ownView={view==='own'} group={group} setGroup={setGroup} listingSearch={listingSearch} setListingSearch={setListingSearch} sort={sort} setSort={setSort} page={page} setPage={setPage} inspect={setSelected}/>;
 return <SidebarProvider style={{'--sidebar-width':'238px'} as React.CSSProperties}><Toaster richColors position="bottom-right"/><Sidebar className="app-sidebar"><SidebarHeader><a href="/" className="brand"><span className="brand-mark"><ScanLine size={23}/></span><span>market<span className="brand-light">lens</span><small>COMPETITIVE INTELLIGENCE</small></span></a><div className="workspace"><span className="workspace-icon">US</span><div><strong>US Auto Nation</strong><small>Seat cover workspace</small></div><ChevronRight size={15}/></div></SidebarHeader><SidebarContent><SidebarGroup><div className="nav-label">WORKSPACE</div><SidebarMenu>{NAV.map(({key,label,icon:Icon})=><SidebarMenuItem key={key}><SidebarMenuButton isActive={view===key} onClick={()=>setView(key)} className="nav-button"><Icon/><span>{label}</span>{key==='coverage'&&gaps.length>0&&<b>{gaps.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup><div className="nav-label recent-label">TRACKED VEHICLES <Bell size={13}/></div>{tracking.tracks.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(t=><button key={t.id} className={'history-item tracked-model '+(activeTrack===t.id&&view==='history'?'active':'')} onClick={()=>{setActiveTrack(t.id);setView('history')}}><Package size={14}/><span>{t.name}<small>{t.plan.minYear??'All'}–{t.plan.maxYear??'years'} · {t.enabled?t.status:'Paused'}</small></span>{t.unread>0&&<b>{t.unread}</b>}</button>)}{!tracking.tracks.length&&<div className="history-empty">Analyze a product to start tracking it.</div>}<div className="tracking-note">Shared history · refresh every 24 hours</div></SidebarGroup></SidebarContent><SidebarFooter><div className="sidebar-note"><ShieldCheck size={20}/><strong>Clear comparisons.</strong><p>Reference sellers never influence competitor pricing.</p></div><button className="sidebar-sources" onClick={()=>setSourceOpen(true)}><Globe2 size={17}/><span>Sources & collection</span><ChevronRight size={15}/></button><div className="user-area"><span className="avatar">US</span><div><strong>Research workspace</strong><small>Shared repository data</small></div></div></SidebarFooter></Sidebar>
 <main className="main"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger/><span>Workspace</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="topbar-right"><Button variant="ghost" size="icon" className="notification-bell" aria-label={`${unreadTotal} unread competitor updates`} onClick={()=>setView('history')}><Bell size={18}/>{unreadTotal>0&&<b>{unreadTotal}</b>}</Button><span className="public-label"><Globe2 size={14}/> Public sources</span><Button variant="outline" onClick={exportData} disabled={exporting||!all.length}><ArrowDownToLine size={16}/>{exporting?'Exporting…':'Export research'}</Button></div></header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow">RESEARCH WORKSPACE</div><h1>{title}</h1><p>{view==='history'?'Tracked vehicles, historical observations, and competitor price changes.':view==='overview'?'See the market. Find your next opportunity.':view==='pricing'?'Compare prices within the same fitment and product configuration.':view==='coverage'?'Discover options not yet observed in your collected catalog.':view==='own'?'Your accounts, kept separate from competitor benchmarks.':'Your business rules, organized into three distinct groups.'}</p></div><button className="text-button" onClick={()=>setSourceOpen(true)}><Clock3 size={15}/>{date(research.createdAt)}<ChevronRight size={15}/></button></div>
 <form className="research-search" onSubmit={analyze}><div className="search-leading"><Search size={22}/></div><div className="search-input"><label htmlFor="product-query">PRODUCT OR VEHICLE</label><Input id="product-query" value={query} maxLength={160} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Chevy Corvette 2005–2013" disabled={busy}/></div><div className="search-scope"><Globe2 size={15}/><span>{COLLECTION_SOURCES.filter(s=>s.channel!=='unconfigured').length} public sources</span></div><Button className="analyze-button" type="submit" disabled={busy||!!queryError}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {busy?'Analyzing…':'Analyze market'}{!busy&&<ArrowRight size={16}/>}</Button></form>
 {queryError?<p className="search-validation">{queryError}</p>:pendingPlan?.years.length?<div className="year-window"><Search size={15}/><span>This search includes <strong>{pendingPlan.minYear}–{pendingPlan.maxYear}</strong> · one adjacent year on each side</span></div>:null}
 {busy&&<div className="collection-progress" role="status"><LoaderCircle className="spin" size={16}/><span>Searching all expanded years · {progress} of {COLLECTION_SOURCES.length} source checks complete</span><div><i style={{width:progress/COLLECTION_SOURCES.length*100+'%'}}/></div></div>}
 {pendingPlan&&<KnownItems query={query} track={tracking.tracks.find(t=>t.key===pendingPlan!.key)} busy={busy} onSaved={refreshTracking}/>}
 {error&&<div className="error-banner" role="alert"><TriangleAlert size={17}/><span>{error}</span>{unsaved&&<Button variant="outline" size="sm" onClick={()=>save(research)}>Retry save</Button>}</div>}
 <CoverageSummary sources={sourceList} busy={busy} onDetails={()=>setSourceOpen(true)}/><div className="research-context"><span className="context-label">CURRENT RESEARCH</span><strong>{research.query}</strong><span className="snapshot-badge">Public-page snapshot</span><button onClick={()=>setSourceOpen(true)}>{observedSellerCount} sellers observed <ArrowUpRight size={13}/></button></div>
 {view!=='directory'&&view!=='history'&&<><div className="filter-bar"><span className="filter-label"><SlidersHorizontal size={16}/> Filter by</span><Pick label="Colors" value={color} onChange={setColor} options={[...new Set(all.map(r=>r.color))].sort()}/><Pick label="Materials" value={material} onChange={setMaterial} options={[...new Set(all.map(r=>r.material))].sort()}/><Pick label="Configurations" value={config} onChange={setConfig} options={[...new Set(all.map(r=>r.configuration))].sort()}/><Pick label="Years" value={year} onChange={setYear} options={[...new Set(all.flatMap(r=>r.years))].sort().map(String)}/><Pick label="Sellers" value={seller} onChange={setSeller} options={[...new Set(all.map(r=>r.seller))].sort()}/>{currencies.length>1&&<Pick label="Currencies" value={currency} onChange={setCurrency} options={currencies}/>}<button className="filter-reset" onClick={reset} disabled={!filtersActive}>Reset</button><Button variant="ghost" size="icon" aria-label="Color normalization rules" onClick={()=>setRulesOpen(true)}><Palette size={17}/></Button></div>
 <div className="stat-grid"><Stat label="Primary competitor observations" value={primary.length} sub={`${new Set(primary.map(r=>r.seller)).size} of 9 price competitors observed`} icon={Users}/><Stat label="Median eligible item price" value={currency==='all'?'Select currency':money(metrics.median,currency)} sub={`${metrics.count} priced variants · configurations may differ`} icon={BarChart3}/><Stat label="Color & material pairs" value={knownSegments.size} sub="Distinct combinations in collected results" icon={Palette}/><Stat label="Potential catalog gaps" value={gaps.length} sub="Verify against your complete catalog" icon={Target} tone="blue-text"/></div></>}
 {view==='history'&&<DataHistory index={tracking} activeTrack={activeTrack} research={research} onTrack={setActiveTrack} onRun={loadHistory} onAcknowledge={ids=>trackingAction({action:'acknowledge',ids})} onToggle={(id,enabled)=>trackingAction({action:'toggle',id,enabled})} onRefresh={q=>analyze(undefined,q)}/>}
 {view==='overview'&&coverage.length>0&&<div className="year-window" style={{marginBottom:20}}><span><strong>Observed fitment by year</strong> · green = found, gray = not observed</span><div className="year-chips">{coverage.map(y=><span title={`${y.year}: ${y.found?'observed':'not observed'}${y.adjacent?' · adjacent year':''}`} key={y.year} className={'year-chip '+(y.found?'found ':'')+(y.adjacent?'adjacent':'')}>{y.year}</span>)}</div></div>}
 {view==='overview'&&<><div className="overview-grid"><section className="panel distribution-panel"><div className="panel-heading"><div><h2>Primary competitor price spread</h2><p>Item prices across eligible variants · {currency==='all'?'select one currency':currency}</p></div><span className="tiny-badge">Observed sample</span></div>{comparable.length&&currency!=='all'?<><div className="price-landmarks"><div><span>Lowest</span><strong>{money(metrics.min,currency)}</strong></div><div><span>Median</span><strong>{money(metrics.median,currency)}</strong></div><div><span>Highest</span><strong>{money(metrics.max,currency)}</strong></div></div><div className="histogram" role="img" aria-label="Histogram of eligible primary competitor item prices across configurations">{Array.from({length:10},(_,i)=>{const range=(metrics.max!-metrics.min!)||1;const min=metrics.min!+range*i/10,max=metrics.min!+range*(i+1)/10;const count=comparable.filter(r=>r.price!>=min&&(i===9?r.price!<=max:r.price!<max)).length;const maxCount=Math.max(...Array.from({length:10},(_,j)=>comparable.filter(r=>r.price!>=metrics.min!+range*j/10&&(j===9?r.price!<=metrics.max!:r.price!<metrics.min!+range*(j+1)/10)).length),1);return <div className="hist-column" key={i} title={`${money(min)}–${money(max)}: ${count} variants`}><span>{count||''}</span><i style={{height:Math.max(count/maxCount*95,count?5:0)+'px',background:i<3?'#adc4fa':i<6?'#6d9cf3':'#3473e6'}}/></div>})}</div><div className="hist-axis"><span>{money(metrics.min,currency)}</span><span>Item price ({currency})</span><span>{money(metrics.max,currency)}</span></div><div className="panel-footnote"><Info size={13}/> Mixed configurations. Use Price intelligence for comparable segments.</div></>:<Empty title="No comparable prices yet">Unknown attributes and reference sellers are excluded.</Empty>}</section><section className="opportunity-panel"><div className="opportunity-heading"><span><Target size={19}/> Coverage opportunities</span><span className="opportunity-count">{gaps.length}</span></div><h2>A wider view of your catalog.</h2><p>These configurations appear in the market sample but were not observed in your collected listings.</p><div className="opportunity-list">{gaps.slice(0,3).map(s=><button key={s.key} onClick={()=>{setColor(s.sample.color);setMaterial(s.sample.material);setConfig(s.sample.configuration);setView('coverage')}}><span className="color-dot" style={{background:SWATCH[s.sample.color]||'#ccc'}}/><span><strong>{s.label}</strong><small>{s.sample.configuration}</small></span><ChevronRight size={16}/></button>)}{!gaps.length&&<p>No confirmed combinations to flag in the current sample.</p>}</div><button className="opportunity-action" onClick={()=>setView('coverage')}>Explore catalog coverage <ArrowRight size={16}/></button></section></div>{listingTable}</>}
 {view==='pricing'&&<><div className="info-note"><ShieldCheck size={18}/><p><strong>Primary competitors only.</strong> Each segment matches color, material, configuration, finish, model, years, currency, and condition. Shipping is excluded. Recommendations need at least 3 listings from 2 price competitors.</p></div><section className="panel"><div className="panel-heading"><div><h2>Segment pricing</h2><p>Prices are comparable only within a row. Values are item prices, before shipping and tax.</p></div><span className="tiny-badge">{seg.length} exact segments</span></div>{seg.length?<Table><TableHeader><TableRow><TableHead>COLOR / MATERIAL</TableHead><TableHead>CONFIGURATION / FITMENT</TableHead><TableHead>SAMPLE</TableHead><TableHead className="right">LOWEST</TableHead><TableHead className="right">AVERAGE</TableHead><TableHead className="right">MEDIAN</TableHead><TableHead className="right">HIGHEST</TableHead><TableHead className="right">BALANCED*</TableHead></TableRow></TableHeader><TableBody>{seg.map(s=><TableRow key={s.key}><TableCell><strong>{s.sample.color}</strong><small className="block muted">{s.sample.material}</small></TableCell><TableCell>{s.sample.configuration}<small className="block muted">{s.sample.finish} · {s.sample.years[0]}–{s.sample.years.at(-1)}</small></TableCell><TableCell>{s.count} variants<small className="block muted">{s.sellers} price sellers</small></TableCell><TableCell className="right">{money(s.min,s.sample.currency)}</TableCell><TableCell className="right">{money(s.mean,s.sample.currency)}</TableCell><TableCell className="right"><strong>{money(s.median,s.sample.currency)}</strong></TableCell><TableCell className="right">{money(s.max,s.sample.currency)}</TableCell><TableCell className="right">{money(s.balanced,s.sample.currency)}<small className="block muted">{s.balanced===null?'Insufficient sample':'Heuristic'}</small></TableCell></TableRow>)}</TableBody></Table>:<Empty title="No segments available"/>}<div className="panel-footnote">* Balanced = median × 0.98. Export includes aggressive (minimum × 0.99) and premium (75th percentile). These are scenarios; costs and margins are not included.</div></section><div className="info-note demand"><Activity size={18}/><p><strong>Best-selling products: not established.</strong> These public feeds do not expose verified product sales. Listing counts and store-wide sales cannot establish demand or a sales ranking.</p></div>{listingTable}</>}
 {view==='coverage'&&<><div className="info-note"><Info size={18}/><p><strong>Coverage is provisional.</strong> We have public observations from {new Set(all.filter(r=>r.group==='own').map(r=>r.seller)).size} of your 7 accounts. An unobserved option is a research lead, not proof of a catalog gap. Unknown attributes never establish a gap.</p></div><section className="panel"><div className="panel-heading"><div><h2>Color & material coverage</h2><p>Observed variants by normalized color and material. Select a cell to inspect that combination.</p></div><div className="matrix-legend"><span><i className="legend-own"/>Own observed</span><span><i className="legend-gap"/>Market only</span><span><i className="legend-empty"/>Not observed</span></div></div><div className="matrix-scroll"><table className="coverage-matrix"><thead><tr><th>COLOR</th>{[...new Set(filtered.filter(r=>r.material!=='Unknown').map(r=>r.material))].sort().map(m=><th key={m}>{m}</th>)}</tr></thead><tbody>{[...new Set(filtered.filter(r=>r.color!=='Unknown').map(r=>r.color))].sort().map(c=><tr key={c}><th><span className="color-label"><i style={{background:SWATCH[c]||'#ccc'}}/>{c}</span></th>{[...new Set(filtered.filter(r=>r.material!=='Unknown').map(r=>r.material))].sort().map(m=>{const rs=filtered.filter(r=>r.color===c&&r.material===m),o=rs.filter(r=>r.group==='own').length,n=rs.filter(r=>r.group==='primary'||r.group==='reference').length;return <td key={m}><button className={'matrix-cell '+(o?'covered':n?'missing':'unseen')} onClick={()=>{setColor(c);setMaterial(m)}}><strong>{o?'Observed':n?'Market only':'—'}</strong><small>{n||o?`${o} own · ${n} market`:'No observation'}</small></button></td>})}</tr>)}</tbody></table></div></section><section className="panel"><div className="panel-heading"><div><h2>Options to investigate <span className="count-pill">{gaps.length}</span></h2><p>Exact configuration gaps within this partial public sample.</p></div></div>{gaps.length?<div className="gap-grid">{gaps.slice(0,24).map(s=><div className="gap-card" key={s.key}><span className="tiny-badge amber">Not observed in our sample</span><h3><i style={{background:SWATCH[s.sample.color]||'#ddd'}}/>{s.label}</h3><p>{s.sample.configuration} · {s.sample.finish}</p><div>{s.sample.years[0]}–{s.sample.years.at(-1)} <span>{s.market} market variants</span></div><button onClick={()=>setSelected(s.rows.find(r=>r.group!=='own')||s.rows[0])}>Inspect evidence <ArrowUpRight size={15}/></button></div>)}</div>:<Empty title="No potential gaps in this view">This reflects only known attributes in the collected sample.</Empty>}{gaps.length>24&&<div className="panel-footnote">Showing 24 of {gaps.length}. Apply filters or export all segments.</div>}</section>{listingTable}</>}
 {view==='own'&&<><div className="info-note"><Package size={18}/><p><strong>Seven accounts, one catalog.</strong> Own-account listings never enter competitor price statistics. All seven accounts are included in collection. US Auto Nation is searched through its website and eBay account. Check source results for access failures or incomplete coverage.</p></div>{listingTable}</>}
 {view==='directory'&&<div className="directory-grid">{(['own','primary','reference'] as Group[]).map(g=><section className={'panel directory-panel '+g} key={g}><div className="directory-head"><span className="directory-icon">{g==='own'?<Package/>:g==='primary'?<BarChart3/>:<Palette/>}</span><h2>{GROUP_NAMES[g]}</h2><p>{g==='own'?'Your catalog. Excluded from competitor benchmarks.':g==='primary'?'The only sellers used for pricing benchmarks.':'Variation research. Always excluded from pricing.'}</p><span className="tiny-badge">{SELLERS.filter(s=>s.group===g).length} accounts</span></div>{SELLERS.filter(s=>s.group===g).map(s=><div className="directory-seller" key={s.name}><div><strong>{s.name}</strong><small>{s.adapter&&s.ebay?'Website + eBay':s.ebay?'eBay public search':s.adapter?'Website public search':'Public store link needed'}</small></div><AccountLinks seller={s}/></div>)}</section>)}<div className="directory-note"><ShieldCheck size={18}/><p>Classification is based on your COMPETITOR CLASSIFICATION SYSTEM document. Unrecognized sellers stay outside pricing until explicitly classified.</p></div></div>}
 <footer className="content-footer"><span><ShieldCheck size={14}/> Reference sellers excluded from pricing</span><span>Sources, not assumptions. <button onClick={()=>setSourceOpen(true)}>Review data coverage <ArrowUpRight size={12}/></button></span></footer>
 </div></main>
 <Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="detail-sheet"><SheetHeader><div className="eyebrow">LISTING EVIDENCE</div><SheetTitle>{selected?.title}</SheetTitle><SheetDescription>{selected?.seller} · {selected&&GROUP_NAMES[selected.group]}</SheetDescription></SheetHeader>{selected&&<div className="detail-content">{selected.image&&<div className="detail-image"><img src={selected.image} alt="Product image from the source store" onError={e=>{e.currentTarget.style.display='none'}}/></div>}<div className="detail-price">{money(selected.price,selected.currency)}<span>Item price · {selected.available===false?'out of stock':selected.available===true?'available':'availability unknown'}</span></div><div className="detail-fields">{[['Variation coverage',selected.variationCoverage?.replaceAll('_',' ')||'Not recorded'],['Published choices',selected.variationOptions?.map(o=>o.name+': '+o.values.join(' / ')).join('; ')||'Not exposed'],['Variant',selected.variant||'Not published'],['Configuration',selected.configuration],['Vehicle',selected.model],['Years',selected.years.join(', ')||'Unknown'],['Finish',selected.finish],['Original color',selected.originalColor],['Normalized color',selected.color],['Color evidence',selected.colorEvidence],['Original material',selected.originalMaterial],['Normalized material',selected.material],['Material evidence',selected.materialEvidence],['Shipping',money(selected.shipping,selected.currency)],['Sales volume',selected.sold??'Not published'],['Collected',date(selected.collectedAt)]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div>{selected.group==='own'&&(()=>{const peers=stats(all.filter(r=>segmentKey(r)===segmentKey(selected)));return <div className="info-note"><BarChart3 size={17}/><p>Comparable primary median: {money(peers.median,selected.currency)}<br/>{selected.price!==null&&peers.median!==null?`Your item-price gap: ${money(selected.price-peers.median,selected.currency)}`:'A price gap needs an exact own price and comparable primary listings.'}</p></div>})()}<div className="detail-warnings">{selected.warnings.map((w,i)=><p key={i}><Info size={14}/>{w}</p>)}</div><a className="source-link" href={selected.url} target="_blank" rel="noreferrer">Open original product page <ExternalLink size={16}/></a><p className="muted detail-url">{selected.url}</p></div>}</SheetContent></Sheet>
 <Dialog open={sourceOpen} onOpenChange={setSourceOpen}><DialogContent className="sources-dialog"><DialogHeader><DialogTitle>Sources & collection</DialogTitle><DialogDescription>Live public pages from supported stores. Searches are bounded and may be incomplete.</DialogDescription></DialogHeader><SourceReports sources={sourceList} busy={busy}/><div className="info-note"><Info size={17}/><p>Every registered account is included in the collection report. eBay security checks stop automated requests and are shown as blocked. Price ranges and unknown currencies are excluded from exact-price comparisons. Accounts without a confirmed link are listed separately.</p></div><Button onClick={()=>{setSourceOpen(false);analyze()}} disabled={busy}><RefreshCw size={16}/> Refresh public pages</Button></DialogContent></Dialog>
 <Dialog open={rulesOpen} onOpenChange={setRulesOpen}><DialogContent className="rules-dialog"><DialogHeader><DialogTitle>Color normalization rules</DialogTitle><DialogDescription>Map observed color aliases into comparison groups. Original values are retained. Changes apply to the current snapshot and are saved as a new run.</DialogDescription></DialogHeader><label htmlFor="color-rules">Alias → normalized color</label><textarea id="color-rules" value={rulesText} onChange={e=>setRulesText(e.target.value)} spellCheck={false}/><p className="muted">Confirm equivalence using OEM trim codes. Edit these mappings when colors differ on a specific vehicle.</p>{ruleError&&<p role="alert" className="red-text">{ruleError}</p>}<Button onClick={applyRules}>Apply to this research</Button></DialogContent></Dialog>
 </SidebarProvider>;
}
